
name: volume
description: Volume plugin to control device VOLUME for Android. Pull request for IOS implementation is welcome. 
version: 1.0.1
homepage: https://github.com/aman-malhotra-1999/Volume_Flutter.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.0
dependencies:
  flutter:
    sdk: flutter
    
  system_shortcuts: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.volume
        pluginClass: VolumePlugin
